const crypto = require('crypto');

/**
 * Short, unique-ish codes for ambulances / patients / sessions.
 * Mongo doesn't auto-increment, so codes are generated by combining a prefix,
 * a base36 timestamp, and a random suffix. Uniqueness is enforced by a unique
 * index on the column.
 */
function generateCode(prefix) {
  const ts = Date.now().toString(36).toUpperCase();
  const rand = crypto.randomBytes(2).toString('hex').toUpperCase();
  return `${prefix}-${ts}-${rand}`;
}

module.exports = { generateCode };
